## @file
# File templates/pr-gate-build-job.yml
#
# template file used to build supported packages.
#
# Copyright (c) Microsoft Corporation.
# Copyright (c) 2020 - 2021, ARM Limited. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

parameters:
  tool_chain_tag: ''
  vm_image: ''
  arch_list: ''

# Build step
jobs:

- job: Build_${{ parameters.tool_chain_tag }}

# EDK2_PLATFORMS_MODIF_START:
# Build edk2-platforms packages
  #Use matrix to speed up the build process
  strategy:
    matrix:
      TARGET_ARM_PLATFORMS:
        Build.Pkgs: 'JunoPkg'
        Build.Targets: 'DEBUG,RELEASE,NO-TARGET,NOOPT'
# EDK2_PLATFORMS_MODIF_END

  workspace:
    clean: all

  pool:
    vmImage: ${{ parameters.vm_image }}

  steps:
  - template: pr-gate-steps.yml
    parameters:
      tool_chain_tag: ${{ parameters.tool_chain_tag }}
      build_pkgs: $(Build.Pkgs)
      build_targets: $(Build.Targets)
      build_archs: ${{ parameters.arch_list }}
